dubbo:
  application:
    name: plague-log
    id: plague-log
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://124.220.173.67:8848?namespace=plague-dev
    check: false
  cloud:
    subscribed-services: plague-mq
  provider:
    loadbalance: roundrobin
  consumer:
    check: false
    timeout: 5000
    retries: 3

