spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      default-binder: kafka
      bindings:
        api_access_log_output:
          destination: plague_api_access_log
          contentType: application/json

dubbo:
  application:
    name: plague-mq
    id: plague-mq
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://124.220.173.67:8848?namespace=plague-dev
    check: false
  cloud:
    subscribed-services:
  provider:
    loadbalance: roundrobin
  consumer:
    check: false
    timeout: 5000
    retries: 3
