spring:
  # ??? Sleuth + ZipKin
  sleuth:
    web:
      client:
        # ???? webClient
        enabled: true
    sampler:
      probability: 1.0 # ??????? 0.1 ???? 1.0
  zipkin:
    enabled: true
    base-url: http://127.0.0.1:9411/ # ???Zipkin??????
    # ????????
    discoveryClientEnabled: false
    sender:
      #  ???????web ??? HTTP ????????????????kafka ?ACTIVEMQ ?
      type: web