#配置 - nacos config
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: qwe123..
#    url: jdbc:mysql://127.0.0.1:3306/plague_warehouse?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    type: com.alibaba.druid.pool.DruidDataSource
#    # ????
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#
#mybatis-plus:
#  mapperLocations: classpath:/mapper/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#

#dubbo:
#  application:
#    name: plague-warehouse
#    id: plague-warehouse
#  protocol:
#    #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
#    name: dubbo
#    #dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
#    port: -1
#  registry:
#    #dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
#    #其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
#    address: spring-cloud://192.168.1.20:8848?namespcae=9071eadb-60b5-4ea9-964f-6f2343df6a28
#    check: false
#  cloud:
#    subscribed-services:
#  provider:
#    loadbalance: roundrobin
#  consumer:
#    #关闭注册中心是否启动的相关检查,false表示不检查注册中心是否启动，就不会报错
#    check: false
#    timeout: 5000
#    retries: 3
