spring:
  cloud:
    sentinel:
      transport:
        port: 8080
        dashboard: localhost:8080
      # Nacos 动态数据源, 动态控制限流阈值
      datasource:
        ds1:
          nacos:
            server-addr: 124.220.173.67:8848
            username: nacos
            password: nacos
            dataId: plague-warehouse-flow-rule-dev
            namespace: plague-dev
            groupId: PLAGUE
            data-type: json
            rule-type: flow
    # 使用 Ribbon
    loadbalancer:
      ribbon:
        enabled: true
    # 网关
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 路由服务
      routes:
        # 订单模块
        - id: plague-order
          uri: lb://plague-order
          predicates:
            - Path= /api/order/**
        # 仓库模块
        - id: plague-warehouse
          uri: lb://plague-warehouse
          predicates:
            - Path= /api/warehouse/**
        # 用户模块
        - id: plague-user
          uri: lb://plague-user
          predicates:
            - Path= /api/user/**
        # 认证模块
        - id: plague-auth
          uri: lb://plague-auth
          predicates:
            - Path= /auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://127.0.0.1:9095/rsa/publicKey' #配置RSA的公钥访问地址
      # CORS 跨域请求
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-headers: "*"
#            allow-credentials: true
#            allowed-methods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTION
  main:
    allow-bean-definition-overriding: true

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"

dubbo:
  application:
    name: plague-gateway
    id: plague-gateway
  protocol:
    #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
    name: dubbo
    #dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；
    #如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
    port: -1
  registry:
    #其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
    #dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
    address: spring-cloud://124.220.173.67:8848?namespace=plague-dev
    check: false
  cloud:
    subscribed-services: plague-cache
  provider:
    loadbalance: roundrobin
  consumer:
    #关闭注册中心是否启动的相关检查,false表示不检查注册中心是否启动，就不会报错
    check: false
    timeout: 5000
    retries: 3