spring:
  cloud:
    sentinel:
      transport:
        port: 8080
        dashboard: localhost:8080
      # 动态数据源
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.20:8848
            username: nacos
            password: nacos
            dataId: plague-sentinel-datasource
            namespace: 9071eadb-60b5-4ea9-964f-6f2343df6a28
            groupId: PLAGUE
            data-type: json
            rule-type: flow
    # 使用 Ribbon
    loadbalancer:
      ribbon:
        enabled: true
    # 网关
    gateway:
      # 定位发现
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 路由服务
      routes:
        # 订单路由
        - id: plague-order
          uri: lb://plague-order
          predicates:
            - Path= /api/order/**
        # 仓库路由
        - id: plague-warehouse
          uri: lb://plague-warehouse
          predicates:
            - Path= /api/warehouse/**

      # CORS 跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
  main:
    allow-bean-definition-overriding: true