spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 20  #?????????????????8
        max-wait: -1    #???????????????????-1
        max-idle: 8     #?????????8
        min-idle: 0     #?????????0
    timeout: 3000ms

dubbo:
  application:
    name: plague-cache
    id: plague-cache
  protocol:
    #Dubbo ??????????????? name ??????port ?????? -1 ???????? 20880 ???
    name: dubbo
    #dubbo???????20880?rmi???????1099?http?hessian???????80???????port????????????????-1????????????????Dubbo 2.4.0+???????????????????????????
    port: -1
  registry:
    #dubbo????????????????????????????9090???????????????????ip:port,ip:port
    #????spring-cloud?????? Spring Cloud????
    address: spring-cloud://192.168.1.20:8848?namespace=9071eadb-60b5-4ea9-964f-6f2343df6a28
    check: false
#  cloud:
#    subscribed-services:
  provider:
    loadbalance: roundrobin
  consumer:
    #???????????????,false???????????????????
    check: false
    timeout: 5000
    retries: 3