spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000ms

dubbo:
  application:
    name: plague-cache
    id: plague-cache
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://124.220.173.67:8848?namespace=plague-dev
    check: false
#  cloud:
#    subscribed-services:
  provider:
    loadbalance: roundrobin
  consumer:
    check: false
    timeout: 5000
    retries: 3